# Generated by Django 3.2.6 on 2021-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
